version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APP_KEY=${APP_KEY}
      - TZ=${TZ:-UTC}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-3333}
      - DRIVE_DISK=${DRIVE_DISK:-spaces}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - APP_PASSWORD=${APP_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
