version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3333}:3333"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - APP_KEY=${APP_KEY}
      - TZ=${TZ:-UTC}
      - HOST=0.0.0.0
      - PORT=3333
      - DRIVE_DISK=${DRIVE_DISK:-spaces}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - APP_PASSWORD=${APP_PASSWORD}
    labels:
      - coolify.port=3333
      - coolify.healthcheck.path=/health
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3333/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
