version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - APP_KEY=${APP_KEY}
      - HOST=0.0.0.0
      - PORT=3000
      - DRIVE_DISK=${DRIVE_DISK:-spaces}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - APP_PASSWORD=${APP_PASSWORD}
      - LOG_LEVEL=info
