version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000'
    environment:
      - NODE_ENV=production
      - APP_KEY=${APP_KEY}
      - HOST=0.0.0.0
      - PORT=3000
      - DRIVE_DISK=${DRIVE_DISK:-spaces}
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - APP_PASSWORD=${APP_PASSWORD}
      - LOG_LEVEL=info
    labels:
      - coolify.healthcheck.path=/health
      - coolify.healthcheck.port=3000
      - coolify.healthcheck.interval=10s
      - coolify.protocol=http
      - traefik.enable=true
      - traefik.http.services.${COOLIFY_SERVICE_NAME:-webhook}.loadbalancer.server.port=3000
    healthcheck:
      test:
        ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
